project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: '.'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  - source: '/src/i18n/catalogs/source/en.json'
    translation: '/src/i18n/catalogs/generated/%locale%.json'
  - source: '/docs/content/en/**/*.mdx'
    translation: '/docs/content/%locale%/**/%original_file_name%'
  - source: '/docs/content/en/**/*.json'
    translation: '/docs/content/%locale%/**/%original_file_name%'
