import { describe, expect, it } from 'vitest';

import type { DocsManifest } from '@/docs/evidence/manifest';
import {
  buildInventoryGraph,
  renderGeneratedFiles,
  validateManifestShape,
  validateModel,
} from '../../../../scripts/docs-evidence-pipeline';
import type { AppSurface } from '../../../../scripts/docs-evidence-pipeline';

const baseManifest: DocsManifest = {
  id: 'demo',
  title: 'Demo Feature',
  module: 'Demo',
  owner: 'demo-owner',
  releaseState: 'released',
  summary: 'Demo feature evidence.',
  routes: ['/demo', '/api/demo'],
  permissions: ['demo:read'],
  workflows: [{ id: 'demo.workflow', title: 'Demo workflow', summary: 'Run the demo workflow.' }],
  actions: [{ id: 'demo.action', title: 'Demo action', summary: 'Run the demo action.' }],
  apis: [{ id: 'demo.api', method: 'GET', route: '/api/demo', summary: 'Read demo data.' }],
  errors: [{ code: 'AFD-DEMO-ERROR', title: 'Demo error', mitigation: 'Fix the demo setup.' }],
  troubleshooting: [
    {
      id: 'demo-troubleshooting',
      title: 'Demo troubleshooting',
      symptom: 'Demo fails.',
      resolution: 'Review demo configuration.',
    },
  ],
};

const surfaces: AppSurface[] = [
  { file: 'src/app/demo/page.tsx', kind: 'page', route: '/demo' },
  { file: 'src/app/api/demo/route.ts', kind: 'api', route: '/api/demo' },
];

describe('docs evidence pipeline', () => {
  it('validates manifest schema and release states', () => {
    const errors = validateManifestShape({ ...baseManifest, releaseState: 'manual' });

    expect(errors.some((error) => error.startsWith('releaseState:'))).toBe(true);
  });

  it('detects missing route and permission coverage', () => {
    const errors = validateModel({
      manifests: [{ ...baseManifest, routes: ['/demo'], permissions: [] }],
      manifestFiles: ['src/features/demo/docs.manifest.ts'],
      appSurfaces: surfaces,
      discoveredPermissions: ['demo:read'],
    });

    expect(errors).toContain('route "/api/demo" (src/app/api/demo/route.ts) has no docs manifest coverage.');
    expect(errors).toContain('permission "demo:read" has no docs manifest coverage.');
  });

  it('builds a normalized inventory graph from valid product truth', () => {
    const graph = buildInventoryGraph({
      manifests: [baseManifest],
      manifestFiles: ['src/features/demo/docs.manifest.ts'],
      appSurfaces: surfaces,
      discoveredPermissions: ['demo:read'],
    });

    expect(graph.generated).toBe(true);
    expect(graph.coverage.routes['/api/demo']).toEqual(['demo']);
    expect(graph.coverage.permissions['demo:read']).toEqual(['demo']);
    expect(graph.hash).toMatch(/^[a-f0-9]{64}$/);
  });

  it('renders generated MDX and JSON with immutable generated markers', () => {
    const graph = buildInventoryGraph({
      manifests: [baseManifest],
      manifestFiles: ['src/features/demo/docs.manifest.ts'],
      appSurfaces: surfaces,
      discoveredPermissions: ['demo:read'],
    });
    const files = renderGeneratedFiles(graph);

    const featurePage = files.find(
      (file) => file.path.endsWith('features\\demo.mdx') || file.path.endsWith('features/demo.mdx'),
    );
    const inventory = files.find((file) => file.path.endsWith('docs-inventory.generated.json'));

    expect(featurePage?.content).toContain('GENERATED FILE - DO NOT EDIT');
    expect(featurePage?.content).toContain('Generated by: pnpm docs:generate');
    expect(inventory?.content).toContain('"generated": true');
  });
});
