#!/bin/bash
# =============================================================================
# Post-create script for Afenda DevContainer
# This script runs after the container is created
# =============================================================================

set -e

echo "🚀 Setting up Afenda development environment..."

# Navigate to workspace
cd /workspaces/*

# -----------------------------------------------------------------------------
# Install dependencies
# -----------------------------------------------------------------------------
echo "📦 Installing dependencies with pnpm..."
# Use --force to avoid interactive prompts about existing node_modules
pnpm install --force

# -----------------------------------------------------------------------------
# Setup managed environment
# -----------------------------------------------------------------------------
echo "🔧 Configuring environment..."

set_env_value() {
    local key="$1"
    local value="$2"
    local escaped_value
    escaped_value=$(printf '%s' "$value" | sed 's/[&|]/\\&/g')

    if grep -qE "^#?${key}=" env.config; then
        sed -i "s|^#\\?${key}=.*|${key}=${escaped_value}|g" env.config
    else
        printf '\n%s=%s\n' "$key" "$value" >> env.config
    fi
}

created_env_config=false
if [ ! -f env.config ]; then
    echo "📝 Creating env.config from env.config.example..."
    cp env.config.example env.config
    created_env_config=true
else
    echo "ℹ️  env.config already exists, preserving local values..."
fi

set_env_value "DATABASE_URL" "postgresql://saas_app:saas_app@db:5432/afenda_dev"
set_env_value "S3_ENDPOINT" "http://minio:9000"
set_env_value "S3_PUBLIC_ENDPOINT" "http://localhost:9000"

if [ "$created_env_config" = true ] || ! grep -qE '^AUTH_SECRET=.+' env.config; then
    AUTH_SECRET=$(openssl rand -base64 32)
    set_env_value "AUTH_SECRET" "$AUTH_SECRET"
    echo "✅ AUTH_SECRET generated in env.config"
else
    echo "ℹ️  AUTH_SECRET already exists in env.config, preserving it"
fi

echo "🔄 Syncing .env.local from env.config..."
pnpm env:sync

# -----------------------------------------------------------------------------
# Setup database
# -----------------------------------------------------------------------------
echo "🗄️  Waiting for database to be ready..."
until pg_isready -h db -p 5432 -U saas_app -d afenda_dev > /dev/null 2>&1; do
    echo "   Waiting for PostgreSQL..."
    sleep 2
done

echo "🗄️  Applying database migrations..."
pnpm db:migrate

# -----------------------------------------------------------------------------
# Setup MinIO bucket
# -----------------------------------------------------------------------------
echo "📦 Setting up MinIO bucket..."

# Wait for MinIO to be ready
until curl -sf http://minio:9000/minio/health/live > /dev/null 2>&1; do
    echo "   Waiting for MinIO..."
    sleep 2
done

# Configure mc (MinIO Client) and create bucket
mc alias set afenda http://minio:9000 saas_app saas_app123 2>/dev/null || true
mc mb afenda/afenda-uploads --ignore-existing 2>/dev/null || true
mc anonymous set download afenda/afenda-uploads 2>/dev/null || true

# Configure CORS for browser uploads
echo "🔧 Configuring MinIO CORS policy..."
cat > /tmp/cors.json << 'EOF'
{
  "CORSRules": [
    {
      "AllowedHeaders": ["*"],
      "AllowedMethods": ["GET", "PUT", "POST", "DELETE", "HEAD"],
      "AllowedOrigins": ["*"],
      "ExposeHeaders": ["ETag", "x-amz-meta-*"]
    }
  ]
}
EOF
mc anonymous set-json /tmp/cors.json afenda/afenda-uploads 2>/dev/null || \
  echo "   (CORS may need manual setup via MinIO console)"
rm -f /tmp/cors.json

echo "✅ MinIO bucket 'afenda-uploads' ready"

# -----------------------------------------------------------------------------
# Done!
# -----------------------------------------------------------------------------
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "  ✅ Afenda development environment is ready!"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "  Environment is managed by env.config; .env.local is generated by pnpm env:sync"
echo ""
echo "  Available commands:"
echo "    pnpm dev          - Start Next.js development server"
echo "    pnpm db:studio    - Open Drizzle Studio (database GUI)"
echo "    pnpm build        - Build for production"
echo "    pnpm test         - Run tests"
echo "    pnpm lint         - Run linter"
echo ""
echo "  Database connection:"
echo "    Host: db (or localhost from outside container)"
echo "    Port: 5432"
echo "    User: saas_app"
echo "    Database: afenda_dev"
echo ""
echo "  To customize environment: edit env.config, then run pnpm env:sync"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
