import fg from 'fast-glob';
import { Project, SyntaxKind } from 'ts-morph';
import { z } from 'zod';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { pathToFileURL } from 'node:url';

import { docsReleaseStates } from '../src/docs/evidence/manifest';
import type { DocsManifest } from '../src/docs/evidence/manifest';

const ROOT = process.cwd();
const ENGLISH_DOCS_ROOT = join(ROOT, 'docs/content/en');
const GENERATED_ROOT = join(ENGLISH_DOCS_ROOT, 'generated');
const SEARCH_SITE_ROOT = join(ROOT, '.artifacts/docs-search-site');
const MANIFEST_PATTERNS = ['src/docs/docs.manifest.ts', 'src/features/*/docs.manifest.ts'];
const APP_SURFACE_PATTERNS = ['src/app/**/page.tsx', 'src/app/**/route.ts'];
const GENERATED_HEADER = `{/*
GENERATED FILE - DO NOT EDIT
Source: docs inventory graph
Generated by: pnpm docs:generate
*/}`;

const methodSchema = z.enum(['DELETE', 'GET', 'PATCH', 'POST', 'PUT']);
const manifestSchema = z.object({
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  title: z.string().min(1),
  module: z.string().min(1),
  owner: z.string().min(1),
  releaseState: z.enum(docsReleaseStates),
  summary: z.string().min(1),
  routes: z.array(z.string().min(1)).min(1),
  permissions: z.array(z.string().min(1)),
  workflows: z.array(
    z.object({
      id: z.string().min(1),
      title: z.string().min(1),
      summary: z.string().min(1),
    }),
  ),
  actions: z.array(
    z.object({
      id: z.string().min(1),
      title: z.string().min(1),
      summary: z.string().min(1),
    }),
  ),
  apis: z.array(
    z.object({
      id: z.string().min(1),
      method: methodSchema,
      route: z.string().min(1),
      summary: z.string().min(1),
    }),
  ),
  errors: z.array(
    z.object({
      code: z.string().regex(/^AFD-[A-Z0-9-]+$/),
      title: z.string().min(1),
      mitigation: z.string().min(1),
    }),
  ),
  troubleshooting: z.array(
    z.object({
      id: z.string().min(1),
      title: z.string().min(1),
      symptom: z.string().min(1),
      resolution: z.string().min(1),
    }),
  ),
});

export function validateManifestShape(input: unknown): string[] {
  const parsed = manifestSchema.safeParse(input);
  if (parsed.success) return [];
  return parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`);
}

export interface AppSurface {
  file: string;
  route: string;
  kind: 'api' | 'page';
}

export interface DocsInventoryGraph {
  generated: true;
  version: 1;
  doctrine: string;
  hash: string;
  generatedFrom: {
    manifests: string[];
    appSurfaces: string[];
    permissions: string[];
  };
  manifests: DocsManifest[];
  coverage: {
    routes: Record<string, string[]>;
    permissions: Record<string, string[]>;
  };
}

interface ValidationModel {
  manifests: DocsManifest[];
  manifestFiles: string[];
  appSurfaces: AppSurface[];
  discoveredPermissions: string[];
}

interface RenderedFile {
  path: string;
  content: string;
}

function toPosixPath(path: string): string {
  return path.split(sep).join('/');
}

function normalizeRoute(route: string): string {
  if (route === '') return '/';
  return route.startsWith('/') ? route : `/${route}`;
}

function routeFromAppFile(file: string): AppSurface {
  const normalized = toPosixPath(file);
  const kind = normalized.endsWith('/route.ts') ? 'api' : 'page';
  const withoutRoot = normalized.replace(/^src\/app\//, '').replace(/(?:^|\/)(?:page\.tsx|route\.ts)$/, '');
  const segments = withoutRoot
    .split('/')
    .filter((segment) => segment.length > 0)
    .filter((segment) => !(segment.startsWith('(') && segment.endsWith(')')));
  return {
    file: normalized,
    route: normalizeRoute(segments.join('/')),
    kind,
  };
}

export function discoverAppSurfaces(root = ROOT): AppSurface[] {
  const surfaces = fg
    .sync(APP_SURFACE_PATTERNS, { cwd: root, onlyFiles: true })
    .map(routeFromAppFile)
    .sort((a, b) => a.route.localeCompare(b.route) || a.file.localeCompare(b.file));

  const expanded = [...surfaces];
  for (const surface of surfaces) {
    if (surface.kind === 'page' && surface.route.endsWith('/[[...slug]]')) {
      expanded.push({
        ...surface,
        route: surface.route.slice(0, -'/[[...slug]]'.length) || '/',
      });
    }
  }

  return expanded.sort((a, b) => a.route.localeCompare(b.route) || a.file.localeCompare(b.file));
}

export function discoverPermissions(root = ROOT): string[] {
  const project = new Project({
    tsConfigFilePath: join(root, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });
  const files = fg.sync(['src/**/*.{ts,tsx}'], {
    cwd: root,
    ignore: ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/**/*.stories.tsx'],
  });
  project.addSourceFilesAtPaths(files.map((file) => join(root, file)));

  const out = new Set<string>();
  for (const sourceFile of project.getSourceFiles()) {
    for (const call of sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression)) {
      const expression = call.getExpression().getText();
      if (!expression.endsWith('requirePermission') && !expression.endsWith('hasPermission')) continue;
      const permissionArg = call.getArguments()[1];
      if (!permissionArg || !permissionArg.isKind(SyntaxKind.StringLiteral)) continue;
      out.add(permissionArg.getLiteralText());
    }
  }
  return [...out].sort();
}

export async function loadManifestModel(root = ROOT): Promise<ValidationModel> {
  const manifestFiles = fg.sync(MANIFEST_PATTERNS, { cwd: root, onlyFiles: true }).sort();
  const manifests: DocsManifest[] = [];
  const errors: string[] = [];

  for (const file of manifestFiles) {
    const fullPath = join(root, file);
    const cacheKey = statSync(fullPath).mtimeMs;
    const imported = await import(`${pathToFileURL(fullPath).href}?v=${cacheKey}`);
    const parsed = manifestSchema.safeParse(imported.default);
    if (!parsed.success) {
      errors.push(
        `${file}: ${parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ')}`,
      );
      continue;
    }
    manifests.push(parsed.data);
  }

  if (errors.length > 0) {
    throw new Error(errors.join('\n'));
  }

  manifests.sort((a, b) => a.id.localeCompare(b.id));
  return {
    manifests,
    manifestFiles,
    appSurfaces: discoverAppSurfaces(root),
    discoveredPermissions: discoverPermissions(root),
  };
}

function addIndex(map: Map<string, string[]>, key: string, manifestId: string) {
  const existing = map.get(key) ?? [];
  existing.push(manifestId);
  map.set(key, existing);
}

export function validateModel(model: ValidationModel): string[] {
  const errors: string[] = [];
  const routes = new Set(model.appSurfaces.map((surface) => surface.route));
  const routeCoverage = new Map<string, string[]>();
  const permissionCoverage = new Map<string, string[]>();
  const duplicateIds = new Map<string, string[]>();

  for (const manifest of model.manifests) {
    for (const route of manifest.routes) {
      if (!routes.has(route)) {
        errors.push(`${manifest.id}: route "${route}" is not present in src/app.`);
      }
      addIndex(routeCoverage, route, manifest.id);
    }

    for (const permission of manifest.permissions) {
      if (!model.discoveredPermissions.includes(permission)) {
        errors.push(`${manifest.id}: permission "${permission}" is not used by requirePermission()/hasPermission().`);
      }
      addIndex(permissionCoverage, permission, manifest.id);
    }

    for (const api of manifest.apis) {
      if (!manifest.routes.includes(api.route)) {
        errors.push(`${manifest.id}: api "${api.id}" route "${api.route}" is not listed in manifest.routes.`);
      }
      if (!routes.has(api.route)) {
        errors.push(`${manifest.id}: api "${api.id}" route "${api.route}" is not present in src/app.`);
      }
    }

    for (const [kind, ids] of Object.entries({
      manifest: [manifest.id],
      workflow: manifest.workflows.map((item) => item.id),
      action: manifest.actions.map((item) => item.id),
      api: manifest.apis.map((item) => item.id),
      error: manifest.errors.map((item) => item.code),
      troubleshooting: manifest.troubleshooting.map((item) => item.id),
    })) {
      for (const id of ids) {
        const key = `${kind}:${id}`;
        duplicateIds.set(key, [...(duplicateIds.get(key) ?? []), manifest.id]);
      }
    }
  }

  for (const surface of model.appSurfaces) {
    if (!routeCoverage.has(surface.route)) {
      errors.push(`route "${surface.route}" (${surface.file}) has no docs manifest coverage.`);
    }
  }

  for (const permission of model.discoveredPermissions) {
    if (!permissionCoverage.has(permission)) {
      errors.push(`permission "${permission}" has no docs manifest coverage.`);
    }
  }

  for (const [key, owners] of duplicateIds) {
    if (owners.length > 1) {
      errors.push(`duplicate stable id "${key}" appears in manifests: ${owners.join(', ')}.`);
    }
  }

  return errors.sort();
}

export function buildInventoryGraph(model: ValidationModel): DocsInventoryGraph {
  const routeCoverage: Record<string, string[]> = {};
  const permissionCoverage: Record<string, string[]> = {};

  for (const manifest of model.manifests) {
    for (const route of manifest.routes) {
      routeCoverage[route] = [...(routeCoverage[route] ?? []), manifest.id].sort();
    }
    for (const permission of manifest.permissions) {
      permissionCoverage[permission] = [...(permissionCoverage[permission] ?? []), manifest.id].sort();
    }
  }

  const hashInput = JSON.stringify({
    manifests: model.manifests,
    appSurfaces: model.appSurfaces,
    permissions: model.discoveredPermissions,
  });

  return {
    generated: true,
    version: 1,
    doctrine: 'Docs render what product truth declares. Manual prose may explain truth, but it may not define truth.',
    hash: createHash('sha256').update(hashInput).digest('hex'),
    generatedFrom: {
      manifests: model.manifestFiles,
      appSurfaces: model.appSurfaces.map((surface) => surface.file),
      permissions: model.discoveredPermissions,
    },
    manifests: model.manifests,
    coverage: {
      routes: routeCoverage,
      permissions: permissionCoverage,
    },
  };
}

function titleCase(value: string): string {
  return value
    .split(/[-:_/.]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function frontmatter(title: string, description: string): string {
  return `---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(description)}\n---\n\n`;
}

const COMPONENT_IMPORTS = `import { Banner } from 'fumadocs-ui/components/banner';
import { File, Files, Folder } from 'fumadocs-ui/components/files';
import { Step, Steps } from 'fumadocs-ui/components/steps';
import { Tab, Tabs } from 'fumadocs-ui/components/tabs';
import { TypeTable } from 'fumadocs-ui/components/type-table';
`;

function bulletList(items: string[]): string {
  if (items.length === 0) return '- None declared.\n';
  return items.map((item) => `- \`${item}\``).join('\n') + '\n';
}

function textList(items: string[]): string {
  return items.length > 0 ? items.join(', ') : 'None declared';
}

function jsxString(value: string): string {
  return JSON.stringify(value);
}

function jsxValue(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function typeTable(rows: Record<string, { type: string; description: string; required?: boolean }>): string {
  const table = Object.fromEntries(
    Object.entries(rows).map(([name, row]) => [
      name,
      {
        type: row.type,
        description: row.description,
        required: row.required ?? true,
      },
    ]),
  );

  return `<TypeTable type={${jsxValue(table)}} />`;
}

function filesTree(items: string[], folder: string): string {
  if (items.length === 0) {
    return `<Files>
  <Folder name=${jsxString(folder)} defaultOpen>
    <File name="None declared" />
  </Folder>
</Files>`;
  }

  return `<Files>
  <Folder name=${jsxString(folder)} defaultOpen>
${items.map((item) => `    <File name=${jsxString(item)} />`).join('\n')}
  </Folder>
</Files>`;
}

function generatedBanner(id: string, releaseState?: string): string {
  const suffix = releaseState ? ` Release state: ${releaseState}.` : '';
  return `<Banner id=${jsxString(id)} changeLayout={false}>
  GENERATED EVIDENCE - This page is rendered from validated product truth.${suffix}
</Banner>`;
}

function generatedMdx(title: string, description: string, body: string): string {
  return `${frontmatter(title, description)}${COMPONENT_IMPORTS}\n${GENERATED_HEADER}\n${body.trim()}\n`;
}

function renderFeature(manifest: DocsManifest): RenderedFile {
  const body = `
${generatedBanner(`feature-${manifest.id}`, manifest.releaseState)}

## Executive Summary

${manifest.summary}

${typeTable({
  Module: { type: manifest.module, description: 'Product module covered by this evidence page.' },
  Owner: { type: manifest.owner, description: 'Accountable owner for the feature manifest.' },
  'Release state': { type: manifest.releaseState, description: 'Release lifecycle state declared by product truth.' },
  Routes: { type: `${manifest.routes.length} routes`, description: textList(manifest.routes) },
  Permissions: { type: `${manifest.permissions.length} permissions`, description: textList(manifest.permissions) },
})}

<Tabs items={["Routes", "Permissions"]}>
  <Tab>

${filesTree(manifest.routes, 'Routes')}

  </Tab>
  <Tab>

${filesTree(manifest.permissions, 'Permissions')}

  </Tab>
</Tabs>

## Workflows

${manifest.workflows.map((item) => `### ${item.title}\n\n- ID: \`${item.id}\`\n- Summary: ${item.summary}`).join('\n\n') || '- None declared.'}

## Public Actions

${manifest.actions.map((item) => `### ${item.title}\n\n- ID: \`${item.id}\`\n- Summary: ${item.summary}`).join('\n\n') || '- None declared.'}

## Operational Evidence

<Steps>
  <Step>Check the declared owner before changing behavior.</Step>
  <Step>Confirm route, permission, and API references still exist in the product.</Step>
  <Step>Run \`pnpm docs:ci\` after manifest or route changes.</Step>
</Steps>

## APIs

${manifest.apis.map((item) => `- \`${item.method} ${item.route}\` - ${item.summary}`).join('\n') || '- None declared.'}

## Errors

${manifest.errors.map((item) => `- \`${item.code}\` - ${item.title}: ${item.mitigation}`).join('\n') || '- None declared.'}
`;

  return {
    path: join(GENERATED_ROOT, 'features', `${manifest.id}.mdx`),
    content: generatedMdx(manifest.title, manifest.summary, body),
  };
}

function renderGroupedPages(graph: DocsInventoryGraph): RenderedFile[] {
  const files: RenderedFile[] = [];
  const permissions = new Map<string, string[]>();
  const workflows = new Map<string, { title: string; summary: string; feature: string }>();
  const apis = new Map<string, { method: string; route: string; summary: string; feature: string }>();
  const errors = new Map<string, { title: string; mitigation: string; feature: string }>();
  const troubleshooting = new Map<string, { title: string; symptom: string; resolution: string; feature: string }>();

  for (const manifest of graph.manifests) {
    for (const permission of manifest.permissions) {
      permissions.set(permission, [...(permissions.get(permission) ?? []), manifest.id]);
    }
    for (const workflow of manifest.workflows) {
      workflows.set(workflow.id, { title: workflow.title, summary: workflow.summary, feature: manifest.id });
    }
    for (const api of manifest.apis) {
      apis.set(api.id, { method: api.method, route: api.route, summary: api.summary, feature: manifest.id });
    }
    for (const error of manifest.errors) {
      errors.set(error.code, { title: error.title, mitigation: error.mitigation, feature: manifest.id });
    }
    for (const item of manifest.troubleshooting) {
      troubleshooting.set(item.id, {
        title: item.title,
        symptom: item.symptom,
        resolution: item.resolution,
        feature: manifest.id,
      });
    }
  }

  for (const [permission, features] of [...permissions].sort()) {
    files.push({
      path: join(GENERATED_ROOT, 'permissions', `${permission.replace(/[^a-zA-Z0-9-]/g, '-')}.mdx`),
      content: generatedMdx(
        titleCase(permission),
        `Permission evidence for ${permission}.`,
        `${generatedBanner(`permission-${permission.replace(/[^a-zA-Z0-9-]/g, '-')}`)}

## Permission

\`${permission}\`

${typeTable({
  Permission: { type: permission, description: 'Stable permission key discovered from guarded runtime code.' },
  Coverage: { type: `${features.length} features`, description: textList(features) },
})}

## Covered Features

${bulletList(features)}`,
      ),
    });
  }

  for (const [id, workflow] of [...workflows].sort()) {
    files.push({
      path: join(GENERATED_ROOT, 'workflows', `${id}.mdx`),
      content: generatedMdx(
        workflow.title,
        workflow.summary,
        `${generatedBanner(`workflow-${id}`)}

## Workflow Evidence

${typeTable({
  Workflow: { type: id, description: 'Stable workflow ID declared by product truth.' },
  Feature: { type: workflow.feature, description: 'Feature manifest that owns this workflow.' },
})}

<Steps>
  <Step>${workflow.summary}</Step>
  <Step>Confirm route and permission coverage before release-visible changes.</Step>
  <Step>Regenerate evidence with \`pnpm docs:generate\`.</Step>
</Steps>`,
      ),
    });
  }

  for (const [id, api] of [...apis].sort()) {
    files.push({
      path: join(GENERATED_ROOT, 'api', `${id}.mdx`),
      content: generatedMdx(
        titleCase(id),
        api.summary,
        `${generatedBanner(`api-${id}`)}

## API Evidence

${typeTable({
  API: { type: id, description: 'Stable API evidence ID.' },
  Method: { type: api.method, description: 'HTTP method declared in the feature manifest.' },
  Route: { type: api.route, description: 'Next.js route covered by this API evidence.' },
  Feature: { type: api.feature, description: 'Owning feature manifest.' },
})}

## Summary

${api.summary}

${filesTree([`${api.method} ${api.route}`], 'API Route')}`,
      ),
    });
  }

  for (const [code, error] of [...errors].sort()) {
    files.push({
      path: join(GENERATED_ROOT, 'errors', `${code.toLowerCase()}.mdx`),
      content: generatedMdx(
        error.title,
        `Error evidence for ${code}.`,
        `${generatedBanner(`error-${code.toLowerCase()}`)}

## Error Evidence

${typeTable({
  Code: { type: code, description: 'Registered error code.' },
  Feature: { type: error.feature, description: 'Feature manifest that owns the error.' },
})}

## Mitigation

${error.mitigation}`,
      ),
    });
  }

  for (const [id, item] of [...troubleshooting].sort()) {
    files.push({
      path: join(GENERATED_ROOT, 'troubleshooting', `${id}.mdx`),
      content: generatedMdx(
        item.title,
        item.symptom,
        `${generatedBanner(`troubleshooting-${id}`)}

## Troubleshooting Evidence

${typeTable({
  Case: { type: id, description: 'Stable troubleshooting case ID.' },
  Feature: { type: item.feature, description: 'Feature manifest that owns the case.' },
})}

<Steps>
  <Step>Symptom: ${item.symptom}</Step>
  <Step>Resolution: ${item.resolution}</Step>
  <Step>Update the owning feature manifest if product behavior changes.</Step>
</Steps>`,
      ),
    });
  }

  return files;
}

function metaFile(path: string, title: string, pages?: string[]): RenderedFile {
  const payload: Record<string, unknown> = {
    generated: true,
    title,
    source: 'docs inventory graph',
    generatedBy: 'pnpm docs:generate',
  };
  if (pages) {
    for (const page of pages) payload[page] = titleCase(page);
  }
  return { path, content: `${JSON.stringify(payload, null, 2)}\n` };
}

export function renderGeneratedFiles(graph: DocsInventoryGraph): RenderedFile[] {
  const files: RenderedFile[] = [
    {
      path: join(GENERATED_ROOT, 'docs-inventory.generated.json'),
      content: `${JSON.stringify(graph, null, 2)}\n`,
    },
    metaFile(join(GENERATED_ROOT, 'meta.json'), 'Generated Evidence', [
      'features',
      'workflows',
      'permissions',
      'api',
      'errors',
      'troubleshooting',
    ]),
    metaFile(join(GENERATED_ROOT, 'features', 'meta.json'), 'Features'),
    metaFile(join(GENERATED_ROOT, 'workflows', 'meta.json'), 'Workflows'),
    metaFile(join(GENERATED_ROOT, 'permissions', 'meta.json'), 'Permissions'),
    metaFile(join(GENERATED_ROOT, 'api', 'meta.json'), 'API'),
    metaFile(join(GENERATED_ROOT, 'errors', 'meta.json'), 'Errors'),
    metaFile(join(GENERATED_ROOT, 'troubleshooting', 'meta.json'), 'Troubleshooting'),
    ...graph.manifests.map(renderFeature),
    ...renderGroupedPages(graph),
  ];
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

function assertGeneratedHeaders(files: RenderedFile[]): string[] {
  const errors: string[] = [];
  for (const file of files) {
    if (file.path.endsWith('.mdx') && !file.content.includes(GENERATED_HEADER)) {
      errors.push(`${relative(ROOT, file.path)} is missing the generated MDX header.`);
    }
    if (file.path.endsWith('.json')) {
      const parsed = JSON.parse(file.content) as { generated?: unknown; generatedBy?: unknown };
      if (parsed.generated !== true) {
        errors.push(`${relative(ROOT, file.path)} must declare generated=true.`);
      }
    }
  }
  return errors;
}

function writeOrCheck(files: RenderedFile[], check: boolean): string[] {
  const errors: string[] = [];
  const expectedPaths = new Set(files.map((file) => file.path));

  if (existsSync(GENERATED_ROOT)) {
    for (const existing of fg.sync('**/*.{mdx,json}', { cwd: GENERATED_ROOT, onlyFiles: true })) {
      const fullPath = join(GENERATED_ROOT, existing);
      if (!expectedPaths.has(fullPath)) {
        if (check) errors.push(`${relative(ROOT, fullPath)} is stale and should be removed by pnpm docs:generate.`);
      }
    }
  }

  if (!check) {
    rmSync(GENERATED_ROOT, { force: true, recursive: true });
  }

  for (const file of files) {
    if (check) {
      const current = existsSync(file.path) ? readFileSync(file.path, 'utf8') : null;
      if (current !== file.content) {
        errors.push(`${relative(ROOT, file.path)} is stale. Run pnpm docs:generate.`);
      }
      continue;
    }
    mkdirSync(dirname(file.path), { recursive: true });
    writeFileSync(file.path, file.content, 'utf8');
  }

  return errors;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function mdxToSearchText(content: string): string {
  return content
    .replace(/^---[\s\S]*?---\s*/m, '')
    .replaceAll(GENERATED_HEADER, '')
    .replace(/[`*_#[\](){}]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function writeSearchSite(files: RenderedFile[]) {
  rmSync(SEARCH_SITE_ROOT, { force: true, recursive: true });
  for (const file of files.filter((item) => item.path.endsWith('.mdx'))) {
    const rel = toPosixPath(relative(GENERATED_ROOT, file.path)).replace(/\.mdx$/, '.html');
    const outPath = join(SEARCH_SITE_ROOT, rel);
    const titleMatch = file.content.match(/^title:\s+(.+)$/m);
    const title = titleMatch ? JSON.parse(titleMatch[1] ?? '""') : rel.replace(/\.html$/, '');
    const body = mdxToSearchText(file.content);
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>${escapeHtml(title)}</title>
    <meta name="pagefind:route" content="/en/docs/generated/${escapeHtml(rel.replace(/\.html$/, ''))}">
  </head>
  <body data-pagefind-body>
    <h1>${escapeHtml(title)}</h1>
    <main>${escapeHtml(body)}</main>
  </body>
</html>
`;
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, html, 'utf8');
  }
}

function checkSearchOutput(): string[] {
  const required = [join(ROOT, 'public/_pagefind/pagefind.js'), join(ROOT, 'public/_pagefind/pagefind-entry.json')];
  const errors = required
    .filter((file) => !existsSync(file))
    .map((file) => `${relative(ROOT, file)} is missing. Run pnpm docs:search.`);
  const expectedPages = [
    join(SEARCH_SITE_ROOT, 'features/admin.html'),
    join(SEARCH_SITE_ROOT, 'permissions/admin-integrations.html'),
    join(SEARCH_SITE_ROOT, 'troubleshooting/docs-generated-stale.html'),
  ];
  for (const page of expectedPages) {
    if (!existsSync(page)) {
      errors.push(`${relative(ROOT, page)} is missing from the docs search site mirror.`);
    }
  }
  return errors;
}

async function buildCheckedGraph() {
  const model = await loadManifestModel();
  const errors = validateModel(model);
  if (errors.length > 0) {
    throw new Error(errors.join('\n'));
  }
  return buildInventoryGraph(model);
}

function stripLinkSuffix(href: string): string {
  return href.split('#')[0]?.split('?')[0]?.trim() ?? '';
}

function isExternalHref(href: string): boolean {
  return /^(?:https?:|mailto:|tel:|#)/.test(href);
}

function docsPathExists(href: string): boolean {
  const clean = stripLinkSuffix(href).replace(/\/$/, '');
  if (clean === '/docs' || clean === '') return existsSync(join(ENGLISH_DOCS_ROOT, 'index.mdx'));
  if (!clean.startsWith('/docs/')) return true;

  const slug = clean.replace(/^\/docs\//, '').replace(/\.mdx$/, '');
  return existsSync(join(ENGLISH_DOCS_ROOT, `${slug}.mdx`)) || existsSync(join(ENGLISH_DOCS_ROOT, slug, 'index.mdx'));
}

function relativeDocsPathExists(file: string, href: string): boolean {
  const clean = stripLinkSuffix(href);
  if (clean === '' || isExternalHref(clean) || clean.startsWith('/')) return true;

  const base = dirname(file);
  const candidate = join(base, clean.replace(/\.mdx$/, ''));
  return (
    existsSync(candidate) ||
    existsSync(`${candidate}.mdx`) ||
    existsSync(join(candidate, 'index.mdx')) ||
    existsSync(join(base, clean))
  );
}

function extractLinks(content: string): string[] {
  const links = new Set<string>();
  const markdownLink = /\[[^\]]+\]\(([^)]+)\)/g;
  const hrefAttribute = /\shref=["']([^"']+)["']/g;

  for (const match of content.matchAll(markdownLink)) {
    if (match[1]) links.add(match[1]);
  }
  for (const match of content.matchAll(hrefAttribute)) {
    if (match[1]) links.add(match[1]);
  }

  return [...links];
}

function checkDocsLinks(): string[] {
  const errors: string[] = [];
  const files = fg.sync('docs/content/**/*.{md,mdx}', { cwd: ROOT, onlyFiles: true }).sort();

  for (const relFile of files) {
    const file = join(ROOT, relFile);
    const content = readFileSync(file, 'utf8');
    for (const href of extractLinks(content)) {
      if (isExternalHref(href)) continue;
      if (href.startsWith('/docs') && !docsPathExists(href)) {
        errors.push(`${relFile}: internal docs link "${href}" does not resolve.`);
      }
      if (!href.startsWith('/') && !relativeDocsPathExists(file, href)) {
        errors.push(`${relFile}: relative docs link "${href}" does not resolve.`);
      }
    }
  }

  return errors;
}

async function checkLLMExports(): Promise<string[]> {
  const errors: string[] = [];
  const requiredRoutes = [
    'src/app/llms.txt/route.ts',
    'src/app/llms-full.txt/route.ts',
    'src/app/llms.mdx/[locale]/docs/[[...slug]]/route.ts',
    'src/docs/runtime/get-llm-text.ts',
  ];

  for (const route of requiredRoutes) {
    if (!existsSync(join(ROOT, route))) {
      errors.push(`${route} is missing.`);
    }
  }

  const sourceConfig = readFileSync(join(ROOT, 'source.config.ts'), 'utf8');
  if (!sourceConfig.includes('includeProcessedMarkdown: true')) {
    errors.push('source.config.ts must enable includeProcessedMarkdown for LLM exports.');
  }
  if (!sourceConfig.includes('extractLinkReferences: true')) {
    errors.push('source.config.ts must enable extractLinkReferences for link-aware docs quality.');
  }

  const nextConfig = readFileSync(join(ROOT, 'next.config.mjs'), 'utf8');
  if (
    !nextConfig.includes("source: '/:locale/docs/:path*.mdx'") ||
    !nextConfig.includes("destination: '/llms.mdx/:locale/docs/:path*'")
  ) {
    errors.push('next.config.mjs must rewrite /docs/<slug>.mdx to the LLM Markdown route.');
  }

  const llmText = readFileSync(join(ROOT, 'src/docs/runtime/get-llm-text.ts'), 'utf8');
  if (!llmText.includes("getText('processed')")) {
    errors.push('getLLMText must read processed Markdown from Fumadocs.');
  }

  const representative = join(ROOT, 'docs/content/en/generated/features/admin.mdx');
  if (!existsSync(representative)) {
    errors.push('docs/content/en/generated/features/admin.mdx is missing; run pnpm docs:generate.');
  } else {
    const content = readFileSync(representative, 'utf8');
    if (!content.includes('title: "Administration"') || !content.includes('GENERATED FILE - DO NOT EDIT')) {
      errors.push('representative generated docs page is not ready for LLM export.');
    }
  }

  if (!existsSync(join(ROOT, '.source/server.ts'))) {
    errors.push('.source/server.ts is missing; run pnpm docs:source before docs:llms.');
  }

  return errors;
}

async function run(command: string, check: boolean) {
  if (command === 'contract') {
    const model = await loadManifestModel();
    const errors = validateModel(model);
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log(`docs contract passed (${model.manifests.length} manifests, ${model.appSurfaces.length} app surfaces)`);
    return;
  }

  const graph = await buildCheckedGraph();
  const files = renderGeneratedFiles(graph);
  const headerErrors = assertGeneratedHeaders(files);
  if (headerErrors.length > 0) throw new Error(headerErrors.join('\n'));

  if (command === 'inventory') {
    const inventory = files.find((file) => file.path.endsWith('docs-inventory.generated.json'));
    if (!inventory) throw new Error('docs inventory graph was not rendered.');
    if (check) {
      const current = existsSync(inventory.path) ? readFileSync(inventory.path, 'utf8') : null;
      if (current !== inventory.content)
        throw new Error(`${relative(ROOT, inventory.path)} is stale. Run pnpm docs:generate.`);
      console.log('docs inventory graph is current');
    } else {
      mkdirSync(dirname(inventory.path), { recursive: true });
      writeFileSync(inventory.path, inventory.content, 'utf8');
      console.log('docs inventory graph written');
    }
    return;
  }

  if (command === 'generate') {
    const errors = writeOrCheck(files, check);
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log(check ? 'generated docs are current' : `generated ${files.length} docs evidence files`);
    return;
  }

  if (command === 'check') {
    const errors = writeOrCheck(files, true);
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log('docs evidence check passed');
    return;
  }

  if (command === 'search-site') {
    writeSearchSite(files);
    console.log(`docs search site written to ${relative(ROOT, SEARCH_SITE_ROOT)}`);
    return;
  }

  if (command === 'search-check') {
    const errors = checkSearchOutput();
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log('docs search output exists');
    return;
  }

  if (command === 'links') {
    const errors = checkDocsLinks();
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log('docs links are valid');
    return;
  }

  if (command === 'llms') {
    const errors = await checkLLMExports();
    if (errors.length > 0) throw new Error(errors.join('\n'));
    console.log('docs LLM exports are valid');
    return;
  }

  throw new Error(`Unknown docs evidence command "${command}".`);
}

const entry = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (import.meta.url === entry) {
  const command = process.argv[2] ?? 'check';
  const check = process.argv.includes('--check');
  run(command, check).catch((error: unknown) => {
    console.error('docs evidence pipeline failed:\n');
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
